import praw
import requests
import schedule
import time
import logging
import os
import praw
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv() 

# Reddit API credentials

REDDIT_CLIENT_ID = os.getenv('REDDIT_CLIENT_ID')
REDDIT_CLIENT_SECRET = os.getenv('REDDIT_CLIENT_SECRET')
REDDIT_USERNAME = os.getenv('REDDIT_USERNAME')
REDDIT_PASSWORD = os.getenv('REDDIT_PASSWORD')
REDDIT_USER_AGENT = os.getenv('REDDIT_USER_AGENT')

# Groq AI API credentials
GROQ_API_KEY = os.getenv('GROQ_API_KEY')

# Logging configuration
logging.basicConfig(filename='bot.log', level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Reddit authentication
reddit = praw.Reddit(
    client_id=REDDIT_CLIENT_ID,
    client_secret=REDDIT_CLIENT_SECRET,
    username=REDDIT_USERNAME,
    password=REDDIT_PASSWORD,
    user_agent=REDDIT_USER_AGENT
)

def generate_content(prompt):
    """Generate content using Groq AI API."""
    try:
        response = requests.post(
            'https://api.groq.ai/content',
            json={'prompt': prompt},
            headers={'Authorization': f'Bearer {GROQ_API_KEY}'}
        )
        response.raise_for_status()
        return response.json().get('content', 'Default content generated by AI.')
    except requests.exceptions.RequestException as e:
        logging.error(f"Error with Groq API: {e}")
        return "An error occurred while generating content."

def post_to_reddit():
    """Post AI-generated content to Reddit."""
    try:
        subreddit = reddit.subreddit('your_subreddit_name')
        content = generate_content('Generate a daily Reddit post about technology.')
        subreddit.submit(title='Daily AI Post', selftext=content)
        logging.info("Post successfully made to subreddit.")
    except Exception as e:
        logging.error(f"Error posting to Reddit: {e}")

def comment_on_post():
    """Generate and post comments on the latest Reddit post."""
    try:
        subreddit = reddit.subreddit('your_subreddit_name')
        for post in subreddit.new(limit=1):
            comment = generate_content('Generate a thoughtful comment for a Reddit post.')
            post.reply(comment)
            logging.info("Comment successfully posted.")
    except Exception as e:
        logging.error(f"Error commenting on Reddit: {e}")

# Schedule daily posts and comments
schedule.every().day.at("18:35").do(post_to_reddit)
schedule.every().day.at("18:36").do(comment_on_post)

if __name__ == "__main__":
    logging.info("Reddit AI Bot started.")
    print("Reddit Ai Bot started.")
    while True:
        schedule.run_pending()
        time.sleep(1)
